---
title: Skills showcase
format: html
---

Please make a Markdown document in which you showcase the skills you have learned throughout this course. You will do so by analysing your own data using the methods we discussed. 

If you do not have a suitable data set available, you can use openly available data, for example from the `datasets` package in R or the [UCI machine learning repository](https://archive.ics.uci.edu). Please make sure that the data set you choose lends itself to a Bayesian analysis with either shrinkage priors or (weakly) informative priors.

In the Markdown document, analyse your data using either shrinkage or (weakly) informative priors. If you use shrinkage priors, include a prior sensitivity analysis in which you consider alternative shrinkage prior specifications. If you use (weakly) informative priors, include a prior sensitivity analysis in which you vary the degree of informativeness. Go through the WAMBS checklist and include prior and posterior predictive checks. Please describe your findings, the robustness of your results, and your conclusions.

*Important:* If you are participating in this course via IOPS, please email your Markdown document before August 25, 2025 to obtain your credits. 